package com.marklynch.weather.sharedpreferences

const val SHARED_PREFERENCES_USE_CELSIUS = "SHARED_PREFERENCES_USE_CELSIUS"
const val SHARED_PREFERENCES_USE_KM = "SHARED_PREFERENCES_USE_KM"
const val SHARED_PREFERENCES_USE_24_HR_CLOCK = "SHARED_PREFERENCES_USE_24_HR_CLOCK"
const val SHARED_PREFERENCES_LOCATION_ID = "SHARED_PREFERENCES_LOCATION_ID"
